# Use an official Nginx runtime as a base image
FROM nginx:alpine

# Copy the HTML, CSS, and JS files into the container
COPY index_v2.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/
